[tool.ruff]
exclude = ["react-series-data-viewer"]
line-length = 120
preview = true

[tool.ruff.lint]
ignore = ["E202", "E203", "E221", "E241", "E251", "E272"]
# TODO: Add and apply "F", "I", "N", "UP"
select = ["E", "W"]

[tool.pyright]
exclude = ["react-series-data-viewer"]
strict = ["*"]

[tool.pytest.ini-options]
testpaths = ['tests']
